{{- if .Values.model1.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.fullname" . }}-model1
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: model1
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.model1.service.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sentinel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: model1
---
{{- end }}
{{- if .Values.model2.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.fullname" . }}-model2
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: model2
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.model2.service.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sentinel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: model2
---
{{- end }}
{{- if .Values.model3.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.fullname" . }}-model3
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: model3
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.model3.service.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sentinel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: model3
---
{{- end }}
{{- if .Values.model4.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.fullname" . }}-model4
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: model4
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.model4.service.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sentinel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: model4
---
{{- end }}
{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.fullname" . }}-gateway
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sentinel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
{{- end }}
